plugins {
    id 'io.freefair.lombok' version '9.5.0'
    // plugin version set in settings.gradle
    id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin'
    id 'com.github.spotbugs' version '6.5.11'
    id 'com.diffplug.spotless' version '8.10.2'
}

tasks.withType(Checkstyle).configureEach {
    setEnabled(false)
}

spotless {
    java {
        target 'src/**/*.java'
        googleJavaFormat('1.36.1')
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

tasks.named('check') {
    dependsOn tasks.named('spotlessCheck')
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

bootRun {
    systemProperty "spring.profiles.active", "local"
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('**/application*.yml') {
        filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [
            version: project.version.toString()
        ], beginToken: '@', endToken: '@')
    }
}

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsReportingServiceApplication.class'])
        }))
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsReportingServiceApplication.class'])
        }))
    }
}

spotbugs {
    ignoreFailures = true
    effort = 'max'
    reportLevel = 'low'
    excludeFilter = file('spotbugs-exclude.xml')
}

spotbugsMain {
    reports {
        sarif.required = true
        html.required = true
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Vulnerability introduced in spring-boot-starter-logging 4.1.1, overriding until fixed in spring:
    implementation 'ch.qos.logback:logback-classic:1.6.3'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation(platform 'software.amazon.awssdk:bom:2.54.13')
    implementation 'software.amazon.awssdk:s3'
    //AWSSDK:s3 introduces high vuln in netty-codec-http, overriding until fixed in AWS SDK:
    implementation 'io.netty:netty-codec-http:4.2.18.Final'
    implementation 'software.amazon.awssdk:sts'

    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'io.prometheus:prometheus-metrics-exporter-pushgateway'

    // Required for tracing information
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-brave'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'

    implementation 'tools.jackson.dataformat:jackson-dataformat-csv'

    // Hardcoding due to snyk issues raised in CI scan
    implementation 'tools.jackson.core:jackson-databind:3.1.6'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.6'

    runtimeOnly 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly "org.flywaydb:flyway-database-postgresql"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation "org.springframework.boot:spring-boot-starter-flyway-test"
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation "org.testcontainers:testcontainers-localstack"

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.14.0'
}
